spring:
  application:
    name: revive
  datasource:
    # 数据库配置
    url: jdbc:mysql://localhost:3306/fh?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: wr461563root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088

mybatis:
  # xml文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名包扫描
  type-aliases-package: com.example.revivetry.entity
  # 配置文件位置
  config-location: classpath:mybatis-config.xml